### ISSUE TITLE
'secp256k1.h' file not found

### ISSUE THREAD

**Issue by jbsantana2010** [shamatar/secp256k1_swift#2]
Im having an issue with Xcode 12.5, using cocoapods with version 1.0.0.

When compiling project secp256k1.c cant find secp256k1.h header file altough it is on the corresponding header folder.

Ive tried a few things like excluding arm64 arch or only compiling 32 bit archs in build settings but issue continues to be there.

Id appreciate any help with this.

best regards,

**Comment by jbsantana2010** [comment]
no response

**Comment by shamatar** [comment]
@jbsantana2010 As far as I remember cocoapod script was doing preprocessing to modify .h and .c files because building through Cocoapods didn't preserve a folder structure and flattened all the source files into the single folder. It may be related to your issue

**Comment by MajdT51** [comment]
Hi, have the same problem. any solution or good way to fix this problem? , thanks
